// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1EPzM-tDvLJG1N-jjbhkpZCJwlART_k',
    appId: '1:510618833152:web:4dbbd2bee874b2479723e5',
    messagingSenderId: '510618833152',
    projectId: 'al-aqsa-game',
    authDomain: 'al-aqsa-game.firebaseapp.com',
    databaseURL: 'https://al-aqsa-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'al-aqsa-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleNo1wWy5p-i96GEskzc6uzk6bBqEVFk',
    appId: '1:510618833152:android:158c293b40c140ff9723e5',
    messagingSenderId: '510618833152',
    projectId: 'al-aqsa-game',
    databaseURL: 'https://al-aqsa-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'al-aqsa-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqyFIPOm97X_tK0TltUZ5xZxOhgCa3XK4',
    appId: '1:510618833152:ios:1d18187f3a264d239723e5',
    messagingSenderId: '510618833152',
    projectId: 'al-aqsa-game',
    databaseURL: 'https://al-aqsa-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'al-aqsa-game.firebasestorage.app',
    iosBundleId: 'com.example.aqsaKeyGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW1EPzM-tDvLJG1N-jjbhkpZCJwlART_k',
    appId: '1:510618833152:web:cc172e953b4b54279723e5',
    messagingSenderId: '510618833152',
    projectId: 'al-aqsa-game',
    authDomain: 'al-aqsa-game.firebaseapp.com',
    databaseURL: 'https://al-aqsa-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'al-aqsa-game.firebasestorage.app',
  );
}
